### ISSUE TITLE
can't find challenge data

### ISSUE THREAD

**Issue by mehrhardt** [SyneRBI/PETRIC#24]
I downloaded the github repository of the challenge and a docker container (`docker run --rm -it -v data:/mnt/share/petric:ro ghcr.io/synerbi/sirf:edge`). NB: I noticed that the usage was much simpler than described by David [here](https://mediacentral.ucl.ac.uk/Player/C1eAhHAi). Is this video outdated now?

I attached the image to VScode. Somehow the preinstalled conda environments didn't work with my interactive python sessions. This was "easily" fixed by creating a new environment and installing some dependencies (numpy, tensorboardx, deprecation, cil).

When running `$python petric.py` I received an error which I think is due to the data being missing:

```
Traceback (most recent call last):                                                                                                                                                                   
  File "/home/jovyan/work/PETRIC/petric.py", line 139, in <module>                                                                                                                                   
    get_data(srcdir=SRCDIR / "Siemens_mMR_NEMA_IQ", outdir=OUTDIR / "mMR_NEMA")),                                                                                                                    
  File "/home/jovyan/work/PETRIC/petric.py", line 123, in get_data                                                                                                                                   
    acquired_data = STIR.AcquisitionData(str(srcdir / 'prompts.hs'))                                                                                                                                 
  File "/opt/SIRF-SuperBuild/INSTALL/python/sirf/STIR.py", line 1206, in __init__                                                                                                                    
    check_status(self.handle)                                                                                                                                                                        
  File "/opt/SIRF-SuperBuild/INSTALL/python/sirf/Utilities.py", line 451, in check_status                                                                                                            
    raise error(errorMsg)                                                                                                                                                                            
sirf.Utilities.error: ??? "'Error opening file /mnt/share/petric/Siemens_mMR_NEMA_IQ/prompts.hs\\n' exception caught at line 419 of /opt/SIRF-SuperBuild/sources/SIRF/src/xSTIR/cSTIR/cstir.cpp; the reconstruction engine output may provide more information"    
```

**Comment by evgueni-ovtchinnikov** [comment]
to get prompts and other necessary data one needs to run `download_Siemens_mMR_NEMA_IQ.py` (if this data has not been downloaded already) and `prepare_mMR_NEMA_IQ_data.py`

**Comment by KrisThielemans** [comment]
No, we don't anymore. The data sits on the HTTPS server, all prepared.

**Comment by casperdcl** [comment]
The `-v data:/mnt/share/petric:ro` in your command should be modified really...

i.e. if you download https://petric.tomography.stfc.ac.uk/data/ to `/some/folder/data` then you need `-v /some/folder/data:/mnt/share/petric:ro`

**Comment by casperdcl** [comment]
I've documented this in https://github.com/SyneRBI/PETRIC/pull/25 and also I'm currently zipping the folders in https://petric.tomography.stfc.ac.uk/data/ so it's easier to download in one click

**Comment by casperdcl** [comment]
closing as completed; happy to re-open if unclear
