### ISSUE TITLE
CI test run

### ISSUE THREAD

**Issue by gschramm** [SyneRBI/PETRIC#28]
Hi all,

I just registered and @casperdcl created a private repo for me :)

To test the CI (and the leaderboard ;) I just pushed a dummy tag.

But the CI run fails with this [error message](https://github.com/SyneRBI/PETRIC-TeamLeuven1/actions/runs/9746791490/job/26897978881).

```
2024-07-01T15:14:57.2896052Z Current runner version: '2.317.0'
2024-07-01T15:14:57.2902584Z Runner name: 'synerbi@stfc'
2024-07-01T15:14:57.2903428Z Runner group name: 'Default'
2024-07-01T15:14:57.2904344Z Machine name: 'synerbi'
2024-07-01T15:14:57.2908953Z ##[group]GITHUB_TOKEN Permissions
2024-07-01T15:14:57.2911479Z Actions: write
2024-07-01T15:14:57.2912029Z Attestations: write
2024-07-01T15:14:57.2912549Z Checks: write
2024-07-01T15:14:57.2913116Z Contents: write
2024-07-01T15:14:57.2913638Z Deployments: write
2024-07-01T15:14:57.2914161Z Discussions: write
2024-07-01T15:14:57.2914672Z Issues: write
2024-07-01T15:14:57.2915178Z Metadata: read
2024-07-01T15:14:57.2915734Z Packages: write
2024-07-01T15:14:57.2916236Z Pages: write
2024-07-01T15:14:57.2916750Z PullRequests: write
2024-07-01T15:14:57.2917304Z RepositoryProjects: write
2024-07-01T15:14:57.2917907Z SecurityEvents: write
2024-07-01T15:14:57.2918469Z Statuses: write
2024-07-01T15:14:57.2918957Z ##[endgroup]
2024-07-01T15:14:57.2923086Z Secret source: Actions
2024-07-01T15:14:57.2923838Z Prepare workflow directory
2024-07-01T15:14:57.3763263Z Prepare all required actions
2024-07-01T15:14:57.3942344Z Getting action download info
2024-07-01T15:14:57.6347806Z Download action repository 'actions/checkout@v4' (SHA:692973e3d937129bcbf40652eb9f2f61becf3332)
2024-07-01T15:14:58.2395119Z Complete job name: full
2024-07-01T15:15:01.0359792Z ##[group]Run actions/checkout@v4
2024-07-01T15:15:01.0360462Z with:
2024-07-01T15:15:01.0361055Z   fetch-depth: 0
2024-07-01T15:15:01.0361544Z   submodules: recursive
2024-07-01T15:15:01.0362035Z   repository: SyneRBI/PETRIC-TeamLeuven1
2024-07-01T15:15:01.0362893Z   token: ***
2024-07-01T15:15:01.0363345Z   ssh-strict: true
2024-07-01T15:15:01.0363781Z   ssh-user: git
2024-07-01T15:15:01.0364239Z   persist-credentials: true
2024-07-01T15:15:01.0364737Z   clean: true
2024-07-01T15:15:01.0365594Z   sparse-checkout-cone-mode: true
2024-07-01T15:15:01.0366125Z   fetch-tags: false
2024-07-01T15:15:01.0366572Z   show-progress: true
2024-07-01T15:15:01.0367039Z   lfs: false
2024-07-01T15:15:01.0367474Z   set-safe-directory: true
2024-07-01T15:15:01.0367966Z ##[endgroup]
2024-07-01T15:15:01.1812895Z Syncing repository: SyneRBI/PETRIC-TeamLeuven1
2024-07-01T15:15:01.1814901Z ##[group]Getting Git version info
2024-07-01T15:15:01.1815913Z Working directory is '/home/runner01/_work/PETRIC-TeamLeuven1/PETRIC-TeamLeuven1'
2024-07-01T15:15:01.1817661Z Unexpected error attempting to determine if executable file exists '/opt/runner/runner01/miniconda/bin/git': Error: EACCES: permission denied, stat '/opt/runner/runner01/miniconda/bin/git'
2024-07-01T15:15:01.1819913Z Unexpected error attempting to determine if executable file exists '/opt/runner/runner01/miniconda/condabin/git': Error: EACCES: permission denied, stat '/opt/runner/runner01/miniconda/condabin/git'
2024-07-01T15:15:01.1888690Z [command]/usr/bin/git version
2024-07-01T15:15:01.1890696Z git version 2.25.1
2024-07-01T15:15:01.1892813Z ##[endgroup]
2024-07-01T15:15:01.1906575Z Temporarily overriding HOME='/home/runner01/_work/_temp/2a1735bf-fb18-4a0f-b320-1c04fd90e25d' before making global git config changes
2024-07-01T15:15:01.1907846Z Adding repository directory to the temporary git global config as a safe directory
2024-07-01T15:15:01.1909106Z [command]/usr/bin/git config --global --add safe.directory /home/runner01/_work/PETRIC-TeamLeuven1/PETRIC-TeamLeuven1
2024-07-01T15:15:01.1945032Z Deleting the contents of '/home/runner01/_work/PETRIC-TeamLeuven1/PETRIC-TeamLeuven1'
2024-07-01T15:15:01.1950092Z ##[group]Initializing the repository
2024-07-01T15:15:01.1954958Z [command]/usr/bin/git init /home/runner01/_work/PETRIC-TeamLeuven1/PETRIC-TeamLeuven1
2024-07-01T15:15:01.1994268Z Initialized empty Git repository in /home/runner01/_work/PETRIC-TeamLeuven1/PETRIC-TeamLeuven1/.git/
2024-07-01T15:15:01.2005914Z [command]/usr/bin/git remote add origin https://github.com/SyneRBI/PETRIC-TeamLeuven1
2024-07-01T15:15:01.2039156Z ##[endgroup]
2024-07-01T15:15:01.2040673Z ##[group]Disabling automatic garbage collection
2024-07-01T15:15:01.2042592Z [command]/usr/bin/git config --local gc.auto 0
2024-07-01T15:15:01.2070266Z ##[endgroup]
2024-07-01T15:15:01.2071565Z ##[group]Setting up auth
2024-07-01T15:15:01.2079650Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2024-07-01T15:15:01.2108425Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2024-07-01T15:15:01.2338904Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2024-07-01T15:15:01.2361303Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2024-07-01T15:15:01.2595565Z [command]/usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
2024-07-01T15:15:01.2633463Z ##[endgroup]
2024-07-01T15:15:01.2634184Z ##[group]Fetching the repository
2024-07-01T15:15:01.2644415Z [command]/usr/bin/git -c protocol.version=2 fetch --prune --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
2024-07-01T15:15:01.8621593Z From https://github.com/SyneRBI/PETRIC-TeamLeuven1
2024-07-01T15:15:01.8623358Z  * [new branch]      main       -> origin/main
2024-07-01T15:15:01.8624529Z  * [new tag]         v0.0       -> v0.0
2024-07-01T15:15:01.8651250Z [command]/usr/bin/git tag --list v0.0
2024-07-01T15:15:01.8672239Z v0.0
2024-07-01T15:15:01.8679684Z [command]/usr/bin/git rev-parse refs/tags/v0.0
2024-07-01T15:15:01.8706749Z fd7cd97e00a29b5afd1a183420acf47059271693
2024-07-01T15:15:01.8711699Z ##[endgroup]
2024-07-01T15:15:01.8713155Z ##[group]Determining the checkout info
2024-07-01T15:15:01.8714540Z ##[endgroup]
2024-07-01T15:15:01.8715719Z ##[group]Checking out the ref
2024-07-01T15:15:01.8718390Z [command]/usr/bin/git checkout --progress --force refs/tags/v0.0
2024-07-01T15:15:01.8773386Z Note: switching to 'refs/tags/v0.0'.
2024-07-01T15:15:01.8773813Z 
2024-07-01T15:15:01.8776110Z You are in 'detached HEAD' state. You can look around, make experimental
2024-07-01T15:15:01.8777451Z changes and commit them, and you can discard any commits you make in this
2024-07-01T15:15:01.8778373Z state without impacting any branches by switching back to a branch.
2024-07-01T15:15:01.8779029Z 
2024-07-01T15:15:01.8779565Z If you want to create a new branch to retain commits you create, you may
2024-07-01T15:15:01.8780918Z do so (now or later) by using -c with the switch command. Example:
2024-07-01T15:15:01.8781591Z 
2024-07-01T15:15:01.8781895Z   git switch -c <new-branch-name>
2024-07-01T15:15:01.8782261Z 
2024-07-01T15:15:01.8782482Z Or undo this operation with:
2024-07-01T15:15:01.8782946Z 
2024-07-01T15:15:01.8783141Z   git switch -
2024-07-01T15:15:01.8783404Z 
2024-07-01T15:15:01.8783829Z Turn off this advice by setting config variable advice.detachedHead to false
2024-07-01T15:15:01.8784410Z 
2024-07-01T15:15:01.8784655Z HEAD is now at fd7cd97 continue on error
2024-07-01T15:15:01.8786033Z ##[endgroup]
2024-07-01T15:15:01.8786695Z ##[group]Setting up auth for fetching submodules
2024-07-01T15:15:01.8787714Z [command]/usr/bin/git config --global http.https://github.com/.extraheader AUTHORIZATION: basic ***
2024-07-01T15:15:01.8831483Z [command]/usr/bin/git config --global --unset-all url.https://github.com/.insteadOf
2024-07-01T15:15:01.8857226Z [command]/usr/bin/git config --global --add url.https://github.com/.insteadOf git@github.com:
2024-07-01T15:15:01.8884230Z [command]/usr/bin/git config --global --add url.https://github.com/.insteadOf org-16674841@github.com:
2024-07-01T15:15:01.8904710Z ##[endgroup]
2024-07-01T15:15:01.8905537Z ##[group]Fetching submodules
2024-07-01T15:15:01.8908791Z [command]/usr/bin/git submodule sync --recursive
2024-07-01T15:15:01.9153322Z [command]/usr/bin/git -c protocol.version=2 submodule update --init --force --recursive
2024-07-01T15:15:01.9386087Z [command]/usr/bin/git submodule foreach --recursive git config --local gc.auto 0
2024-07-01T15:15:01.9591060Z ##[endgroup]
2024-07-01T15:15:01.9591917Z ##[group]Persisting credentials for submodules
2024-07-01T15:15:01.9594180Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'url\.https\:\/\/github\.com\/\.insteadOf' && git config --local --unset-all 'url.https://github.com/.insteadOf' || :"
2024-07-01T15:15:01.9829121Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local 'http.https://github.com/.extraheader' 'AUTHORIZATION: basic ***' && git config --local --show-origin --name-only --get-regexp remote.origin.url"
2024-07-01T15:15:02.0049880Z [command]/usr/bin/git submodule foreach --recursive git config --local --add 'url.https://github.com/.insteadOf' 'git@github.com:'
2024-07-01T15:15:02.0262807Z [command]/usr/bin/git submodule foreach --recursive git config --local --add 'url.https://github.com/.insteadOf' 'org-16674841@github.com:'
2024-07-01T15:15:02.0499647Z ##[endgroup]
2024-07-01T15:15:02.0530847Z [command]/usr/bin/git log -1 --format='%H'
2024-07-01T15:15:02.0551059Z 'fd7cd97e00a29b5afd1a183420acf47059271693'
2024-07-01T15:15:02.0986374Z ##[group]Run petric
2024-07-01T15:15:02.0986969Z [36;1mpetric[0m
2024-07-01T15:15:02.1003381Z shell: /usr/bin/bash -e {0}
2024-07-01T15:15:02.1003895Z ##[endgroup]
2024-07-01T15:15:02.7167204Z start gadgetron
2024-07-01T15:15:02.7169997Z /opt/SIRF-SuperBuild /w
2024-07-01T15:15:02.7171157Z /w
2024-07-01T15:15:06.6818484Z 
2024-07-01T15:15:06.6836771Z WARNING: RadioNuclideDB::get_radionuclide: unknown modality. Returning "unknown" radionuclide.
2024-07-01T15:15:06.6921485Z 
2024-07-01T15:15:06.6922930Z WARNING: RadioNuclideDB::get_radionuclide: unknown modality. Returning "unknown" radionuclide.
2024-07-01T15:15:06.7536695Z Traceback (most recent call last):
2024-07-01T15:15:06.7537740Z   File "/opt/conda/lib/python3.10/pathlib.py", line 1175, in mkdir
2024-07-01T15:15:06.7549269Z     self._accessor.mkdir(self, mode)
2024-07-01T15:15:06.7556818Z FileNotFoundError: [Errno 2] No such file or directory: '/o/logs/TeamLeuven1/v0.0/mMR_NEMA'
2024-07-01T15:15:06.7557779Z 
2024-07-01T15:15:06.7558639Z During handling of the above exception, another exception occurred:
2024-07-01T15:15:06.7559363Z 
2024-07-01T15:15:06.7559759Z Traceback (most recent call last):
2024-07-01T15:15:06.7560773Z   File "/opt/conda/lib/python3.10/pathlib.py", line 1175, in mkdir
2024-07-01T15:15:06.7561829Z     self._accessor.mkdir(self, mode)
2024-07-01T15:15:06.7563316Z FileNotFoundError: [Errno 2] No such file or directory: '/o/logs/TeamLeuven1/v0.0'
2024-07-01T15:15:06.7564162Z 
2024-07-01T15:15:06.7564995Z During handling of the above exception, another exception occurred:
2024-07-01T15:15:06.7567213Z 
2024-07-01T15:15:06.7567523Z Traceback (most recent call last):
2024-07-01T15:15:06.7568316Z   File "/w/petric.py", line 158, in <module>
2024-07-01T15:15:06.7569383Z     [MetricsWithTimeout(outdir=OUTDIR / "mMR_NEMA", transverse_slice=72, coronal_slice=109)]),
2024-07-01T15:15:06.7570442Z   File "/w/petric.py", line 85, in __init__
2024-07-01T15:15:06.7571194Z     SaveIters(outdir=outdir),
2024-07-01T15:15:06.7571909Z   File "/w/petric.py", line 36, in __init__
2024-07-01T15:15:06.7572778Z     self.outdir.mkdir(parents=True, exist_ok=True)
2024-07-01T15:15:06.7573728Z   File "/opt/conda/lib/python3.10/pathlib.py", line 1179, in mkdir
2024-07-01T15:15:06.7574700Z     self.parent.mkdir(parents=True, exist_ok=True)
2024-07-01T15:15:06.7575610Z   File "/opt/conda/lib/python3.10/pathlib.py", line 1179, in mkdir
2024-07-01T15:15:06.7576518Z     self.parent.mkdir(parents=True, exist_ok=True)
2024-07-01T15:15:06.7577580Z   File "/opt/conda/lib/python3.10/pathlib.py", line 1175, in mkdir
2024-07-01T15:15:06.7578477Z     self._accessor.mkdir(self, mode)
2024-07-01T15:15:06.7579482Z PermissionError: [Errno 13] Permission denied: '/o/logs/TeamLeuven1'
2024-07-01T15:15:07.4173421Z ##[error]Process completed with exit code 1.
2024-07-01T15:15:07.4314307Z Post job cleanup.
2024-07-01T15:15:07.5477304Z Unexpected error attempting to determine if executable file exists '/opt/runner/runner01/miniconda/bin/git': Error: EACCES: permission denied, stat '/opt/runner/runner01/miniconda/bin/git'
2024-07-01T15:15:07.5500329Z Unexpected error attempting to determine if executable file exists '/opt/runner/runner01/miniconda/condabin/git': Error: EACCES: permission denied, stat '/opt/runner/runner01/miniconda/condabin/git'
2024-07-01T15:15:07.5545003Z [command]/usr/bin/git version
2024-07-01T15:15:07.5591749Z git version 2.25.1
2024-07-01T15:15:07.5666778Z Temporarily overriding HOME='/home/runner01/_work/_temp/f2be6136-2b40-47a6-a9d4-22ff7f7815be' before making global git config changes
2024-07-01T15:15:07.5667996Z Adding repository directory to the temporary git global config as a safe directory
2024-07-01T15:15:07.5673536Z [command]/usr/bin/git config --global --add safe.directory /home/runner01/_work/PETRIC-TeamLeuven1/PETRIC-TeamLeuven1
2024-07-01T15:15:07.5723204Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2024-07-01T15:15:07.5755845Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2024-07-01T15:15:07.5993395Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2024-07-01T15:15:07.6014579Z http.https://github.com/.extraheader
2024-07-01T15:15:07.6026382Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2024-07-01T15:15:07.6053299Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2024-07-01T15:15:07.6669813Z Cleaning up orphan processes

```

**Comment by casperdcl** [comment]
Hey @gschramm - can you try restarting the job?

**Comment by gschramm** [comment]
works fine now : https://github.com/SyneRBI/PETRIC-TeamLeuven1/actions/runs/9746791490/job/26905295112
thanks a lot capser!
